#
namespace import -force msgcat::mcset
mcset ru {Usage} {Использование}
mcset ru {device|file} {устройство|файл}
mcset ru {Cancelled.} {Отменено.}
mcset ru {LUKS passphrase input method:} {Способ ввода пароля LUKS:}
mcset ru {OK} {Принять} ;#
mcset ru {Cancel} {Отмена} ;#
mcset ru {Select} {Выберите}
mcset ru {nteractive} { (интерактивно)}
mcset ru {ey File} { (файл с ключом)}
mcset ru {Interactive} {Интерактивно}
mcset ru {Key File} {Файл с ключом}
mcset ru {Select a key file} {Выберите файл с ключом}
mcset ru {Enter root password} {Введите пароль root}
mcset ru {Enter your password} {Введите ваш пароль}
mcset ru {Enter LUKS passphrase for} {Введите LUKS-пароль для}
mcset ru {(no FS)} {(без ФС)}
mcset ru {(no label)} {(без метки)}
mcset ru {Device} {Устройство}
mcset ru {mapped to} {отображено на}
mcset ru {Config error: mounting disabled} \
         {Ошибка конфигурации: монтирование отключено}
mcset ru {mounted on} {смонтировано на}
mcset ru {Config error: unmounting disabled} \
         {Ошибка конфигурации: размонтирование отключено}
mcset ru {released.} {освобождено.}

# eof ru.msg
